import { collection, doc, setDoc, getDocs } from 'firebase/firestore';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { db } from './firebaseConfig';

const STORAGE_KEY = '@jobseeker_jobs_seeded';

const sampleJobs = [
    {
        id: 'job_001',
        title: 'Senior UI/UX Designer',
        company: 'Creative Studios',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 250,000 - 350,000',
        description: 'We are looking for a talented Senior UI/UX Designer to lead our design team.\n\nResponsibilities:\n• Lead the design process from concept to final deliverables\n• Create wireframes, prototypes, and high-fidelity mockups\n• Collaborate with developers to ensure design accuracy',
        category: 'Design',
        type: 'Full-time',
        level: 'Senior',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_002',
        title: 'React Native Developer',
        company: 'TechVision Lanka',
        location: 'Kandy, Sri Lanka',
        salary: 'LKR 200,000 - 300,000',
        description: 'Join our mobile development team as a React Native Developer. Build cross-platform mobile applications.\n\nResponsibilities:\n• Develop and maintain React Native applications\n• Implement pixel-perfect UI components\n• Integrate RESTful APIs and Firebase services',
        category: 'Development',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_003',
        title: 'Digital Marketing Manager',
        company: 'BrandWave Agency',
        location: 'Galle, Sri Lanka',
        salary: 'LKR 180,000 - 250,000',
        description: 'Lead our digital marketing efforts and drive growth across all channels.\n\nResponsibilities:\n• Plan and execute digital marketing campaigns\n• Manage SEO, SEM, and social media strategies',
        category: 'Marketing',
        type: 'Full-time',
        level: 'Senior',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_004',
        title: 'Full Stack Developer',
        company: 'InnovateTech Solutions',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 280,000 - 400,000',
        description: 'We need a Full Stack Developer who can handle both frontend and backend development.\n\nResponsibilities:\n• Build scalable web applications using React and Node.js\n• Design and implement RESTful APIs',
        category: 'Development',
        type: 'Full-time',
        level: 'Senior',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_005',
        title: 'Financial Analyst',
        company: 'Lanka Finance Corp',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 150,000 - 220,000',
        description: 'Analyze financial data and provide insights to support business decisions.\n\nResponsibilities:\n• Prepare financial reports and forecasts\n• Analyze revenue and expense trends',
        category: 'Finance',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_006',
        title: 'Mobile App Developer',
        company: 'AppCraft Studio',
        location: 'Negombo, Sri Lanka',
        salary: 'LKR 160,000 - 240,000',
        description: 'Build amazing mobile apps for iOS and Android using modern frameworks.',
        category: 'Development',
        type: 'Full-time',
        level: 'Junior',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_007',
        title: 'Graphic Designer',
        company: 'PixelPerfect Design',
        location: 'Matara, Sri Lanka',
        salary: 'LKR 120,000 - 180,000',
        description: 'Create stunning visual content for digital and print media.',
        category: 'Design',
        type: 'Full-time',
        level: 'Junior',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_008',
        title: 'Sales Executive',
        company: 'GlobalReach Trading',
        location: 'Kurunegala, Sri Lanka',
        salary: 'LKR 100,000 - 180,000',
        description: 'Identify and pursue new business opportunities.',
        category: 'Sales',
        type: 'Full-time',
        level: 'Entry',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_009',
        title: 'DevOps Engineer',
        company: 'CloudNine Technologies',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 300,000 - 450,000',
        description: 'Manage our cloud infrastructure and CI/CD pipelines.',
        category: 'Engineering',
        type: 'Full-time',
        level: 'Senior',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_010',
        title: 'Content Writer',
        company: 'ContentKing Media',
        location: 'Remote',
        salary: 'LKR 80,000 - 140,000',
        description: 'Create engaging content for blogs and websites.',
        category: 'Marketing',
        type: 'Remote',
        level: 'Entry',
        postedAt: new Date().toISOString(),
    },
    {
        id: 'job_011',
        title: 'Backend Developer (Node.js)',
        company: 'SkyNet Systems',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 180,000 - 280,000',
        description: 'Manage server-side logic and database integration.',
        category: 'Development',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
        id: 'job_012',
        title: 'Frontend Lead',
        company: 'Digital Pulse',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 350,000 - 480,000',
        description: 'Lead frontend development with React and Next.js.',
        category: 'Development',
        type: 'Full-time',
        level: 'Senior',
        postedAt: new Date(Date.now() - 172800000).toISOString(),
    },
    {
        id: 'job_013',
        title: 'Python Developer',
        company: 'AI Lanka',
        location: 'Remote',
        salary: 'LKR 220,000 - 320,000',
        description: 'Develop AI models and backend services with Python.',
        category: 'Development',
        type: 'Remote',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 259200000).toISOString(),
    },
    {
        id: 'job_014',
        title: 'Visual Designer',
        company: 'Studio Arc',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 140,000 - 200,000',
        description: 'Create visual designs for branding and marketing.',
        category: 'Design',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 345600000).toISOString(),
    },
    {
        id: 'job_015',
        title: 'Product Designer',
        company: 'SaaS Solutions',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 280,000 - 380,000',
        description: 'Design end-to-end product experiences.',
        category: 'Design',
        type: 'Full-time',
        level: 'Senior',
        postedAt: new Date(Date.now() - 432000000).toISOString(),
    },
    {
        id: 'job_016',
        title: 'Illustrator',
        company: 'Creative Works',
        location: 'Galle, Sri Lanka',
        salary: 'LKR 90,000 - 150,000',
        description: 'Create unique illustrations for digital assets.',
        category: 'Design',
        type: 'Contract',
        level: 'Junior',
        postedAt: new Date(Date.now() - 518400000).toISOString(),
    },
    {
        id: 'job_017',
        title: 'SEO Specialist',
        company: 'RankUp Media',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 120,000 - 180,000',
        description: 'Optimize websites for search engine rankings.',
        category: 'Marketing',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 604800000).toISOString(),
    },
    {
        id: 'job_018',
        title: 'Social Media Manager',
        company: 'Socially LTD',
        location: 'Remote',
        salary: 'LKR 100,000 - 160,000',
        description: 'Manage social media handles and engagement.',
        category: 'Marketing',
        type: 'Remote',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 691200000).toISOString(),
    },
    {
        id: 'job_019',
        title: 'Growth Marketer',
        company: 'Startup Hub',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 200,000 - 280,000',
        description: 'Drive user acquisition and retention.',
        category: 'Marketing',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 777600000).toISOString(),
    },
    {
        id: 'job_020',
        title: 'Tax Consultant',
        company: 'Accounting Pros',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 180,000 - 250,000',
        description: 'Provide tax planning and compliance services.',
        category: 'Finance',
        type: 'Full-time',
        level: 'Senior',
        postedAt: new Date(Date.now() - 864000000).toISOString(),
    },
    {
        id: 'job_021',
        title: 'Investment Banker',
        company: 'Wealth Management',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 300,000 - 500,000',
        description: 'Manage investment portfolios and financial assets.',
        category: 'Finance',
        type: 'Full-time',
        level: 'Senior',
        postedAt: new Date(Date.now() - 950400000).toISOString(),
    },
    {
        id: 'job_022',
        title: 'Junior Accountant',
        company: 'BizServices',
        location: 'Kandy, Sri Lanka',
        salary: 'LKR 80,000 - 120,000',
        description: 'Maintain financial records and perform bookkeeping.',
        category: 'Finance',
        type: 'Full-time',
        level: 'Junior',
        postedAt: new Date(Date.now() - 1036800000).toISOString(),
    },
    {
        id: 'job_023',
        title: 'Business Development Manager',
        company: 'Enterprise Solutions',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 250,000 - 350,000',
        description: 'Drive business growth and partnerships.',
        category: 'Sales',
        type: 'Full-time',
        level: 'Senior',
        postedAt: new Date(Date.now() - 1123200000).toISOString(),
    },
    {
        id: 'job_024',
        title: 'Real Estate Agent',
        company: 'Homes.lk',
        location: 'Colombo, Sri Lanka',
        salary: 'Commission Based',
        description: 'Help clients buy, sell, and rent properties.',
        category: 'Sales',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 1209600000).toISOString(),
    },
    {
        id: 'job_025',
        title: 'Account Executive',
        company: 'Ad Agency',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 120,000 - 180,000',
        description: 'Manage client accounts and advertising projects.',
        category: 'Sales',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 1296000000).toISOString(),
    },
    {
        id: 'job_026',
        title: 'Software Engineer',
        company: 'Global Tech',
        location: 'Remote',
        salary: 'LKR 280,000 - 450,000',
        description: 'Build robust software solutions.',
        category: 'Engineering',
        type: 'Remote',
        level: 'Senior',
        postedAt: new Date(Date.now() - 1382400000).toISOString(),
    },
    {
        id: 'job_027',
        title: 'Civil Engineer',
        company: 'BuildRight Const.',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 180,000 - 280,000',
        description: 'Oversee construction and infrastructure projects.',
        category: 'Engineering',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 1468800000).toISOString(),
    },
    {
        id: 'job_028',
        title: 'QA Automation Engineer',
        company: 'TestMasters',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 160,000 - 240,000',
        description: 'Automate software testing and quality assurance.',
        category: 'Engineering',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 1555200000).toISOString(),
    },
    {
        id: 'job_029',
        title: 'Network Engineer',
        company: 'Connect LK',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 140,000 - 220,000',
        description: 'Design and maintain network infrastructure.',
        category: 'Engineering',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 1641600000).toISOString(),
    },
    {
        id: 'job_030',
        title: 'Mechanical Engineer',
        company: 'Industrial Tools',
        location: 'Colombo, Sri Lanka',
        salary: 'LKR 150,000 - 230,000',
        description: 'Design and maintain mechanical systems.',
        category: 'Engineering',
        type: 'Full-time',
        level: 'Mid-Level',
        postedAt: new Date(Date.now() - 1728000000).toISOString(),
    },
];

export const seedJobs = async (): Promise<{ success: boolean; dataAdded?: boolean; error?: string }> => {
    try {
        console.log('seedData: Checking Firestore for jobs...');
        const jobsRef = collection(db, 'Jobs');
        const snapshot = await getDocs(jobsRef);
        console.log(`seedData: Current jobs in DB: ${snapshot.size}`);

        // If we have less than 5 jobs, we should definitely seed
        if (snapshot.size < 5) {
            console.log(`seedData: Seeding ${sampleJobs.length} jobs...`);
            // Use simple loop for sample data
            for (const job of sampleJobs) {
                try {
                    await setDoc(doc(db, 'Jobs', job.id), job);
                } catch (err) {
                    console.error(`seedData: Failed to seed job ${job.id}:`, err);
                }
            }
            await AsyncStorage.setItem(STORAGE_KEY, 'true');
            console.log('seedData: Seeding complete.');
            return { success: true, dataAdded: true };
        }

        // Even if we didn't add data, mark as seeded to avoid future counts if needed
        await AsyncStorage.setItem(STORAGE_KEY, 'true');
        return { success: true, dataAdded: false };
    } catch (error: any) {
        console.error('seedData: Error seeding jobs:', error);
        return { success: false, error: error.message };
    }
};

export default sampleJobs;
